[PROTOCOLS]
Virtual Screening = [
    {"tag": "section", "text": "Imports", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Sequences", "openItem": "False", "children": [
        ]}
	]},
	{"tag": "section", "text": "Generic Tasks", "openItem": "False", "children": [
	    {"tag": "protocol_group", "text": "Web databases", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "Format Conversion", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "Protein structure prediction", "openItem": "False", "children": [
        ]},
        {"tag": "protocol_group", "text": "Mutations", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "Operate with Sets", "openItem": "False", "children": [
	    ]},
        {"tag": "protocol_group", "text": "Export", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "Scores", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "Others", "openItem": "False", "children": [
        ]}
	]},
	{"tag": "section", "text": "Library Filters", "openItem": "True", "icon": "bookmark.png", "children": [
	]},
	{"tag": "section", "text": "Ligand Based Filters", "openItem": "False", "children": [
    ]},
    {"tag": "section", "text": "Pharmacophores", "openItem": "False", "children": [
    ]},
	{"tag": "section", "text": "Preparation", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Target Preparation", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "Ligand Preparation", "openItem": "False", "children": [
	    ]}
	]},
    {"tag": "section", "text": "Regions of interest", "icon": "bookmark.png", "children": [
        {"tag": "protocol_group", "text": "ROI operations", "openItem": "False", "children": [
        ]},
        {"tag": "protocol_group", "text": "Protein pockets", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtBioMetAll",   "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "Grids generation", "openItem": "False", "children": [
        ]}
    ]},
    {"tag": "section", "text": "Docking", "icon": "bookmark.png", "children": [
        {"tag": "protocol_group", "text": "Molecular Docking", "openItem": "False", "children": [
        ]},
        {"tag": "protocol_group", "text": "Rescore Docking", "openItem": "False", "children": [
        ]},
        {"tag": "protocol_group", "text": "Protein-Protein Docking", "openItem": "False", "children": [
        ]},
        {"tag": "protocol_group", "text": "Docking validation", "openItem": "False", "children": [
        ]}
	]},
	{"tag": "section", "text": "Lead optimization", "children": [
	]},
	{"tag": "section", "text": "Molecular Dynamics", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "System preparation", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "MD simulation", "openItem": "False", "children": [
	    ]},
	    {"tag": "protocol_group", "text": "Simulation analysis", "openItem": "False", "children": [
	    ]}
	]},
	{"tag": "section", "text": "Sequences protocols", "openItem": "False", "children": [
	    {"tag": "protocol_group", "text": "Sequences", "openItem": "False", "children": [
        ]},
        {"tag": "protocol_group", "text": "Sequence ROIs", "openItem": "False", "children": [
        ]}
	]}
    ]