# **************************************************************************
# *
# * Authors:     Eduardo Rivas Tortuero
# *              Blanca Pueche (blanca.pueche@cnb.csis.es)
# *
# * Unidad de Bioinformatica of Centro Nacional de Biotecnologia, CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************



import json
import os, shutil
import subprocess

from pyworkflow.protocol import Protocol, params
from pyworkflow import BETA
import pyworkflow.object as pwobj
from pwem.convert import cifToPdb

from biometall import Plugin
from biometall.constants import BIOMETALL_DIC
from pwem.protocols import EMProtocol
from pwchem.objects import SetOfStructROIs, StructROI


class ProtMetalScreener(EMProtocol):
    """
        Screens a protein structure for potential metal-binding capability using
        BioMetAll-generated coordination sites and a calibrated Random Forest
        classifier.

        The protocol evaluates candidate metal-binding sites identified by
        BioMetAll using a machine-learning model trained on 62 structural
        features. These features describe the local structural environment,
        including concentric spatial shells, coordination geometry,
        physicochemical properties, and BioMetAll probe density.

        Workflow
        --------
        1. Receive a SetOfStructROIs containing candidate metal-binding sites
           generated by BioMetAll.
        2. Recover the corresponding protein structure from the input ROIs.
        3. Convert the protein structure to PDB format if necessary.
        4. Collect the BioMetAll candidate coordination sites.
        5. Evaluate the candidate sites using the calibrated Random Forest
           classifier.
        6. Assign a metal-binding probability (pMetal) to the candidate sites.
        7. Aggregate the site-level predictions into a protein-level probability.
        8. Classify the protein as a metalloprotein when the protein-level
           probability exceeds the selected decision threshold.
        9. Propagate the predicted site probabilities to the output ROIs.

        Input
        -----
        - inputSites:
            SetOfStructROIs containing candidate metal-binding/coordination sites
            produced by ProtBioMetAll.

            The protein structure associated with the BioMetAll ROIs is used as
            the structure evaluated by the screener.

        Parameters
        ----------
        - Decision threshold:
            Protein-level probability threshold used to classify the input
            structure as a metalloprotein.

            The default value is 0.60. A protein is classified as a
            metalloprotein when its predicted probability is equal to or above
            this threshold.

        Machine Learning Model
        ----------------------
        The protocol uses a calibrated Random Forest classifier specifically
        trained for structural metalloprotein screening.

        The classifier uses 62 three-dimensional structural features describing
        the environment surrounding candidate coordination sites. These include:

        - Local amino-acid composition
        - Concentric spatial shells around the candidate site
        - Metal-coordination geometry
        - Physicochemical properties
        - BioMetAll probe density

        Site-level probabilities are combined into a protein-level score using a
        high-confidence site aggregation strategy based on the 95th percentile
        (p95) of the predicted site probabilities.

        Output
        ------
        - outputStructROIs:
            Copy of the input BioMetAll candidate sites with the predicted
            metal-binding probability stored as the ``pMetal`` attribute of each
            ROI.

        The output ROIs therefore retain the original BioMetAll structural
        information while providing an additional machine-learning-based
        probability for each candidate site.

        Summary
        -------
        The protocol reports:

        - Overall classification:
            Metalloprotein or Non-metalloprotein.

        - pMetal:
            Protein-level probability of being a metalloprotein.

        Use Cases
        ---------
        - Screening proteins for potential metal-binding capability
        - Prioritizing BioMetAll candidate coordination sites
        - Identifying proteins likely to contain functional metal-binding sites
        - Supporting structural metalloprotein annotation
        - Ranking candidate metal-binding sites for further analysis

        Notes
        -----
        This protocol does not identify candidate coordination sites itself.
        Candidate sites must first be generated using BioMetAll and provided as a
        SetOfStructROIs.

        The protein-level classification is based on the predicted probabilities
        of the candidate sites and should therefore be interpreted together with
        the underlying BioMetAll site predictions.

        The decision threshold can be adjusted to control the stringency of the
        metalloprotein classification.
        """

    _label = 'metal-binding sites screening'

    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam(
            'inputSites',
            params.PointerParam,
            pointerClass='SetOfStructROIs',
            label='BioMetAll sites: ',
            important=True,
            help=(
                'SetOfStructROIs produced by ProtBioMetAll. '
                'The corresponding protein structure will be recovered '
                'from the BioMetAll output.'
            )
        )

        form.addParam(
            'tauProtein',
            params.FloatParam,
            default=0.60,
            label='Decision threshold: ',
            help=(
                'Probability threshold used to classify the protein '
                'as a metalloprotein.'
            )
        )

    # ------------------------------------------------------------------
    # Steps
    # ------------------------------------------------------------------
    def _insertAllSteps(self):
        self._insertFunctionStep('convertInputStep')
        self._insertFunctionStep('runScreenerStep')
        self._insertFunctionStep('createOutputStep')

    def convertInputStep(self):
        sites = self.inputSites.get()
        firstSite = sites.getFirstItem()
        filePath = firstSite.getProteinFile()
        proteinName = os.path.splitext(
            os.path.basename(filePath)
        )[0]
        ext = os.path.splitext(filePath)[1].lower()
        outputFile = self._getExtraPath(
            f'{proteinName}.pdb'
        )
        if ext == '.pdb':
            shutil.copy(filePath, outputFile)
        elif ext == '.cif':
            cifToPdb(filePath, outputFile)

    def runScreenerStep(self):
        sites = self.inputSites.get()
        firstSite = sites.getFirstItem()
        proteinFile = firstSite.getProteinFile()

        proteinFile = os.path.abspath(proteinFile)

        probesDir = self._getExtraPath('biometall_sites')
        os.makedirs(
            probesDir,
            exist_ok=True
        )
        for i, site in enumerate(sites):
            source = site.getFileName()
            if not source:
                continue
            destination = os.path.join(
                probesDir,
                'site_%04d.pdb' % i
            )
            shutil.copy2(
                source,
                destination
            )

        probeFiles = [f for f in os.listdir(probesDir) if f.endswith('.pdb')]

        binaryModel = Plugin.getBinaryModelPath()
        if binaryModel is None:
            raise RuntimeError(
                'Binary model not found in: %s\n'
                'Expected: binary_model_*_calibrated.pkl'
                % Plugin.getModelsDir()
            )

        scriptPath = os.path.join(
            Plugin.getBaseDir(),
            'biometall',
            'ml_path0',
            'predict_structural.py'
        )

        jsonOut = self._getPath(
            'screener_result.json'
        )

        args = [
            scriptPath,
            '--pdb', os.path.abspath(self._getExtraPath('*.pdb')),
            '--probes-dir', os.path.abspath(probesDir),
            '--binary-model', binaryModel,
            '--tau', str(self.tauProtein.get()),
            '--output', os.path.abspath(jsonOut)
        ]

        Plugin.runCondaCommand(
            self,
            args=' '.join(args),
            condaDic=BIOMETALL_DIC,
            program='python',
            cwd=os.path.abspath(self._getPath()
            )
        )

        if not os.path.exists(jsonOut):
            raise RuntimeError(
                'Metal Screener did not produce the expected output: %s'
                % jsonOut
            )

    # ------------------------------------------------------------------
    # Outputs
    # ------------------------------------------------------------------
    def createOutputStep(self):
        jsonPath = self._getPath('screener_result.json')
        with open(jsonPath) as fh:
            res = json.load(fh)

        topSites = res.get('top_sites', [])
        inputRois = self.inputSites.get()
        outRois = inputRois.createCopy(self._getPath(), copyInfo=True)

        for roi, site in zip(inputRois, topSites):
            structRoi = roi.clone()
            structRoi.pMetal = pwobj.Float(
                float(site['p_metal'])
            )
            outRois.append(structRoi)

        self._defineOutputs(outputStructROIs=outRois)


    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    def _summary(self):
        summary = []
        jsonPath = self._getPath(
            'screener_result.json'
        )
        with open(jsonPath) as fh:
            res = json.load(fh)
        isMetal = res.get(
            'is_metalloprotein',
            False
        )
        pMetal = res.get(
            'p_metal',
            0.0
        )
        verdict = (
            '*Metalloprotein*'
            if isMetal
            else '*Non-metalloprotein*'
        )
        summary.append(
            'Result: %s' % verdict
        )
        summary.append(
            'pMetal: %.4f' % pMetal
        )
        return summary

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------
    def _validate(self):
        errors = []
        return errors

    # ------------------------------------------------------------------
    # Citations
    # ------------------------------------------------------------------
    def _citations(self):
        return [
            'SanchezAparicio2021',
            'Pedregosa2011',
            'Putignano2018',
            'Cock2009',
        ]

    # ------------------------------------------------------------------
    # Methods
    # ------------------------------------------------------------------
    def _methods(self):
        return [
            (
                'Candidate metal-binding sites were generated using '
                'BioMetAll. The resulting coordination sites were '
                'subsequently evaluated using a calibrated Random Forest '
                'classifier based on 62 structural features including '
                'local amino-acid composition, coordination geometry, '
                'physicochemical environment, and BioMetAll probe density. '
                'Site probabilities were aggregated to a protein-level '
                'score using the 95th percentile (p95) strategy. '
                'The protein was classified as a metalloprotein when the '
                'resulting probability exceeded %.2f.'
            )
            % self.tauProtein.get()
        ]